export const MODULE_KEYS = [
    'home',
    'orders',
    'products',
    'inventory',
    'customers',
    'adPerformance',
    'customerService',
    'callCenter',
    'supplyChain',
    'accounting',
    'analytics',
    'integrations',
    'team',
    'settings',
];
export const ROLE_DEFINITIONS = {
    owner: {
        role: 'owner',
        label: 'Owner',
        description: 'Full access to everything, including billing and team management.',
        modules: [...MODULE_KEYS],
        canManageTeam: true,
        canWrite: true,
    },
    admin: {
        role: 'admin',
        label: 'Admin',
        description: 'Full operational access and can manage the team.',
        modules: [...MODULE_KEYS],
        canManageTeam: true,
        canWrite: true,
    },
    manager: {
        role: 'manager',
        label: 'Manager',
        description: 'Runs day-to-day operations across orders, catalog, and stock.',
        modules: [
            'home',
            'orders',
            'products',
            'inventory',
            'customers',
            'adPerformance',
            'customerService',
            'callCenter',
            'supplyChain',
            'analytics',
        ],
        canManageTeam: false,
        canWrite: true,
    },
    agent: {
        role: 'agent',
        label: 'Order Agent',
        description: 'Confirms orders and handles customer conversations.',
        modules: ['home', 'orders', 'customerService', 'callCenter', 'customers'],
        canManageTeam: false,
        canWrite: true,
    },
    viewer: {
        role: 'viewer',
        label: 'Viewer',
        description: 'Read-only access for reporting and oversight.',
        modules: ['home', 'orders', 'products', 'inventory', 'customers', 'analytics'],
        canManageTeam: false,
        canWrite: false,
    },
};
